name: da
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  awesome_snackbar_content: ^0.1.3
  cloud_firestore: ^4.15.10
  curved_navigation_bar: ^1.0.3
  firebase_auth: ^4.18.0
  firebase_core: ^2.27.2
  firebase_ui_firestore: ^1.6.2
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
